### ISSUE TITLE
Having trouble loading the database.

### ISSUE THREAD

**Issue by jeff-knurek** [tagyoureit/InfluxDB_WDC#4] opened 2017-12-14 13:30 UTC
Our InfluxDB is hosted with https://aiven.io 
which provides parameters for connecting to it, similar to:

key | value
--- | --- 
dbname | defaultdb 
host | service-name.proj-number.aivencloud.com 
password | CLICK_TO_REVEAL 
port | 27254   
user | serviceAccount 

But after filling in the form (unchecking `Use Aggregation`), we're getting:
```Error loading database {"readyState":0,"responseText":"","status":0,"statusText":"error"}```

---

Aiven also provides a "Service URL", like
`https+influxdb://serviceAccount:pwd@service-name.proj-number.aivencloud.com:27254/defaultdb`, but that protocol isn't an option in the form, so haven't tested it without the auth (and doesn't work with curl)

**Comment by tagyoureit** [comment] 2017-12-14 19:02
I just added `https+influxdb://` as a valid protocol.  Hopefully, everything else just works.  Can you test it out and let me know?  If you still have trouble, I'll dig into it a bit more.

**Comment by jeff-knurek** [comment] 2017-12-15 15:52
ok, tried that out and now we have another, more helpful (?) error message:
```{"readyState":0,"status":0,"statusText":"Error: NETWORK_ERR: XMLHttpRequest Exception 101"}```

**Comment by tagyoureit** [comment] 2017-12-15 23:55
It looks like `https+influxdb://` is specific to the InfluxDB clients (Python, Nodejs, etc).  I was able to replicate the issue here, and I've written to Aiven support about how to remediate it.

I believe the problem is Aiven doesn't provide a valid CA Certificate.  If you browse to your server url in the format `https://influx-custom-instance.aivencloud.com:port/` you'll see that the Certificate isn't valid.  
![screen shot 2017-12-15 at 3 26 53 pm](https://user-images.githubusercontent.com/1646840/34064675-e24c812a-e1af-11e7-9dc0-908bb172190d.png)

This also seems to be outlined in [Aiven docs](http://help.aiven.io/influxdb/getting-started-with-aiven-influxdb) where they say to connect via the command line interface to the hosted Influx instance with `-unsafeSsl` (ignoring the invalid certificate warning).  I don't believe there is a programatic way around this using just JQuery/Javascript.

In order to use the aforementioned Influx libraries, I'd have to re-write the whole connector and it would have to be installed locally on a server.  That's not in the plans as of now, so hoping Aiven has a workaround.

**Comment by jeff-knurek** [comment] 2017-12-18 08:34
ok, thanks for looking into it

I have an option of bypassing Influx which has a few other benefits, so will start investigating that instead of waiting for Aiven. I'm not sure what you want to do with this github issue. Maybe edit the title and mark it as closed (won't fix)?

**Comment by tagyoureit** [comment] 2017-12-18 18:20
The response from Aiven regarding the certificates was "On plans that are startup-4 or higher we're currently serving out Letsencrypt certificates. By default we're currently using certificates signed with the customer project's CA. In the future we're actually looking to also use generally trusted certificate throughout our service."  

So sounds like you can pay more (or maybe request a valid cert) and this should work.  I will close this for now.  Thanks for bringing this up!

**Closed as completed by tagyoureit** 2017-12-18 18:20 UTC
